### ISSUE TITLE
mean of these parameter in syslog file

### ISSUE THREAD

**Issue by jindov** [Lax/ngx_http_accounting_module#5]
Mar 23 15:38:09 NgxAccounting: pid:22482|from:1427099859|to:1427099889|accounting_id:default|requests:421|bytes_in:109135|bytes_out:1243987403|200:2|206:419

I don't know what are they: From (where?), to (where?) accounting_id, request for what and bytes_in. byte_out and 200:2|206:419

So could you please give me a doc of this module and how to use this?Thanks in advanced

**Comment by Lax** [comment]
Hi, @jindov,

Just updated README.md, hope it helps.

**Comment by laurretang** [comment]
Here is an example of usage
http://www.itxinxi.net/blog/post/532/
