### ISSUE TITLE
Support for variable in accounting_id

### ISSUE THREAD

**Issue by gmirchev** [Lax/ngx_http_accounting_module#9]
I have a patch that allows something like
    http_accounting_id  $host;

also allows putting any variable. Backwards compatible with normal string. But I can't upload it here, github is buggy.

**Comment by gmirchev** [comment]
So here is link:
https://drive.google.com/open?id=0B6Qb_xPKde3gM3V1azFtZHFtV0k

**Comment by Lax** [comment]
Thank you @gmirchev .
I need permission to view that file in google-drive, please check.

**Comment by gmirchev** [comment]
My mistake. Please try this:
https://drive.google.com/file/d/0B6Qb_xPKde3gM3V1azFtZHFtV0k/view?usp=sharing

**Comment by Lax** [comment]
test case:

    http_accounting on;
    server {
      listen 80;
      server_name localhost;

      http_accounting_id $http_host;

      location / {
        http_accounting_id $uri;
      }
      location /static {
        http_accounting_id static;
      }
    }

when test with `curl http://localhost/static`，the accounting id is not 'static' as expected.

**Comment by Lax** [comment]
I will merge the patch onto master, and later fix the issue above.
